name: Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node (this sets up the cache integration keying off pnpm-lock.yaml later)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      # (Alternative to the above: enable Corepack instead of pnpm/action-setup)
      # - name: Enable Corepack (alternative)
      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@9.0.0 --activate
      #   if: false  # flip to true and remove the pnpm/action-setup step above if you prefer Corepack

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # Cache Next.js build cache
      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with Next.js
        run: pnpm run build

      # If next build does not produce ./out (needs output: 'export' in next.config.mjs),
      # uncomment the export step below:
      # - name: Export static site
      #   run: pnpm exec next export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Site
        id: deployment
        uses: actions/deploy-pages@v4
